# Generated by Django 4.2.1 on 2023-06-10 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nexus_api_point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('bio', models.CharField(max_length=255)),
                ('about', models.TextField(max_length=255)),
                ('rating', models.IntegerField()),
                ('business_name', models.CharField(max_length=255)),
                ('business_category', models.CharField(max_length=255)),
                ('business_reg_no', models.CharField(max_length=255)),
                ('business_logo', models.ImageField(upload_to='logo_images/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ManyToManyField(to='shop_nexus_api_point.customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS42Ibo_SzGpRMi1PRl_c0k0SVj7zSk7KGUujqu1U0S_Q&s', upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_nexus_api_point.seller'),
            preserve_default=False,
        ),
    ]
