# Generated by Django 4.2.2 on 2023-06-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nexus_api_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
