# Generated by Django 4.2.2 on 2023-06-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nexus_api_point', '0002_alter_seller_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
