# Generated by Django 4.2.1 on 2023-06-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nexus_api_point', '0003_remove_product_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_nexus_api_point.seller'),
        ),
    ]
