# Generated by Django 4.2.1 on 2023-06-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nexus_api_point', '0006_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_1',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS42Ibo_SzGpRMi1PRl_c0k0SVj7zSk7KGUujqu1U0S_Q&s', upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_2',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS42Ibo_SzGpRMi1PRl_c0k0SVj7zSk7KGUujqu1U0S_Q&s', upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_3',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS42Ibo_SzGpRMi1PRl_c0k0SVj7zSk7KGUujqu1U0S_Q&s', upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_4',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS42Ibo_SzGpRMi1PRl_c0k0SVj7zSk7KGUujqu1U0S_Q&s', upload_to='product_images/'),
        ),
    ]
