# Generated by Django 4.2.1 on 2023-06-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nexus_api_point', '0007_product_img_1_product_img_2_product_img_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no-product-img', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_1',
            field=models.ImageField(default='no-product-img', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_2',
            field=models.ImageField(default='no-product-img', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_3',
            field=models.ImageField(default='no-product-img', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_4',
            field=models.ImageField(default='no-product-img', upload_to='product_images/'),
        ),
    ]
