# Generated by Django 4.2.1 on 2023-06-12 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nexus_api_point', '0013_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea59814f-16fa-43a2-816e-1f1f521455e3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
