# Generated by Django 4.2.1 on 2023-06-14 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nexus_api_point', '0016_remove_order_customer_remove_order_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderItem',
            new_name='orderitem',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_nexus_api_point.product'),
            preserve_default=False,
        ),
    ]
