# Generated by Django 4.2.2 on 2023-06-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nexus_api_point', '0021_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='orderitem',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_nexus_api_point.orderitem'),
            preserve_default=False,
        ),
    ]
