# Generated by Django 4.2.2 on 2023-06-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nexus_api_point', '0022_payment_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop_nexus_api_point.customer'),
        ),
    ]
