# Generated by Django 4.2.2 on 2023-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nexus_api_point', '0024_alter_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderitem',
        ),
        migrations.AddField(
            model_name='order',
            name='orderitem_list',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
