# Generated by Django 4.2.2 on 2023-06-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_nexus_api_point', '0025_remove_order_orderitem_order_orderitem_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='orderitem',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_nexus_api_point.order'),
            preserve_default=False,
        ),
    ]
